<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Family_Protection_Plan_V0X</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>b4aabb85-da63-496f-9a81-362e114478ef</testSuiteGuid>
   <testCaseLink>
      <guid>5fb004c7-2000-4951-90ab-64bf8038ff15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/End to End flow</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ed073ac8-ddff-47f9-8c9a-0ce2331c4e8f</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>42-67</value>
         </iterationEntity>
         <testDataId>Data Files/TestData/AstraTestData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ed073ac8-ddff-47f9-8c9a-0ce2331c4e8f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Executor</value>
         <variableId>796cf009-01f7-4112-8b24-da48a638ea93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ed073ac8-ddff-47f9-8c9a-0ce2331c4e8f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TC_ID</value>
         <variableId>92547254-7d25-43c1-bd4f-0841487f6037</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
