<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>New_Shri_Life_V03</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7118a56a-4749-4d17-afde-dfcd603832da</testSuiteGuid>
   <testCaseLink>
      <guid>113bab14-c311-4a7d-aadc-a8069ed93438</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/End to End flow</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5c248e1f-b2d7-4195-8e1f-a8229d74d499</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>280-326</value>
         </iterationEntity>
         <testDataId>Data Files/TestData/AstraTestData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>5c248e1f-b2d7-4195-8e1f-a8229d74d499</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Executor</value>
         <variableId>796cf009-01f7-4112-8b24-da48a638ea93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5c248e1f-b2d7-4195-8e1f-a8229d74d499</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TC_ID</value>
         <variableId>92547254-7d25-43c1-bd4f-0841487f6037</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
