<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Pension_Plus_V0X</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>04446c03-0ecc-4564-bc1c-3b6a8c3a8e5b</testSuiteGuid>
   <testCaseLink>
      <guid>b995266f-ce68-43f1-85f0-9822a1a484d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/End to End flow</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>288fcb5c-5d11-4893-bfc0-419bfa780b16</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>316-336</value>
         </iterationEntity>
         <testDataId>Data Files/TestData/AstraTestData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>288fcb5c-5d11-4893-bfc0-419bfa780b16</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Executor</value>
         <variableId>796cf009-01f7-4112-8b24-da48a638ea93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>288fcb5c-5d11-4893-bfc0-419bfa780b16</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TC_ID</value>
         <variableId>92547254-7d25-43c1-bd4f-0841487f6037</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
